// fn prob(player_ture:Player,ai_player:Player)->Unit{
//   if ai_player.direction{//移动
//     if ai_player.pos.x>=player_ture.pos.x+90{ai_player.ai.prob.prob4=80}}
//   else{if ai_player.pos.x<=player_ture.pos.x-70{ai_player.ai.prob.prob4=80}}
//   if ai_player.direction{//攻击
//     if ai_player.pos.x<=player_ture.pos.x+70{ai_player.ai.prob.prob2=50}}
//   else{if ai_player.pos.x>=player_ture.pos.x-50{ai_player.ai.prob.prob2=50}}
//   if ai_player.direction{//防御
//     if ai_player.pos.x<=player_ture.pos.x+50{ai_player.ai.prob.prob3=30}}
//   else{if ai_player.pos.x>=player_ture.pos.x-30{ai_player.ai.prob.prob3=30}}
//   if ai_player.direction{//技能
//     if ai_player.pos.x<=player_ture.pos.x+70{ai_player.ai.prob.prob1=20}}
//   else{if ai_player.pos.x>=player_ture.pos.x-50{ai_player.ai.prob.prob1=20}}
// }